// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RevengeApp.Data;

#nullable disable

namespace RevangesApp.Migrations
{
    [DbContext(typeof(RevengeContext))]
    partial class RevengeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("RevengeApp.Models.Revenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DramaLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Revenges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "AnnoyingCustomer",
                            Date = new DateTime(2025, 6, 2, 19, 51, 32, 130, DateTimeKind.Local).AddTicks(3494),
                            Description = "הלקוחה המעצבנת שהשפילה אותי בפני כולם תקבל את מה שמגיע לה!",
                            DramaLevel = 4,
                            Notes = "צריכה להיות דרמטית במיוחד!",
                            Status = "Planned",
                            Target = "הלקוחה המעצבנת מהדואר",
                            Title = "נקמת השפתון האדום"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
